### ISSUE TITLE
NaN during OXnet training

### ISSUE THREAD

**Issue by johnson111788** [LLYXC/OXnet#4]
Hello

I found that some variables will become NaN during OXnet training. Maybe you can help me to solve this problem.
Again, thanks for your time.

Best,
Johnson

Following is my training log with the variable's value by torch.unique():

x1: tensor([0.0000e+00, 3.3433e-09, 1.0560e-08,  ...,        nan,        nan,        nan], device='cuda:0', grad_fn=<Unique2Backward0>) 
x2: tensor([0.0000e+00, 3.7090e-07, 3.9448e-07,  ...,        nan,        nan,        nan], device='cuda:0', grad_fn=<Unique2Backward0>) 
x3: tensor([0.0000e+00, 8.9078e-05, 1.2970e-04,  ...,        nan,        nan,        nan], device='cuda:0', grad_fn=<Unique2Backward0>) 
x4: tensor([0.0000e+00, 6.8665e-05, 8.6040e-05,  ...,        nan,        nan,        nan], device='cuda:0', grad_fn=<Unique2Backward0>)

ClassificationModel output: torch.Size([4, 128, 128, 9, 1]) tensor([0.0000e+00, 2.9481e-39, 3.1011e-39,  ...,        nan,        nan,
               nan], device='cuda:0', grad_fn=<Unique2Backward0>)
ClassificationModel output: torch.Size([4, 64, 64, 9, 1]) tensor([2.1190e-27, 2.3213e-27, 3.3325e-27,  ...,        nan,        nan,
               nan], device='cuda:0', grad_fn=<Unique2Backward0>)
ClassificationModel output: torch.Size([4, 32, 32, 9, 1]) tensor([1.2803e-13, 3.1964e-13, 7.1933e-13,  ...,        nan,        nan,
               nan], device='cuda:0', grad_fn=<Unique2Backward0>)
ClassificationModel output: torch.Size([4, 16, 16, 9, 1]) tensor([2.0922e-16, 2.1812e-16, 2.8193e-16,  ...,        nan,        nan,
               nan], device='cuda:0', grad_fn=<Unique2Backward0>)
ClassificationModel output: torch.Size([4, 8, 8, 9, 1]) tensor([1.0574e-10, 1.1019e-10, 1.1304e-10,  ...,        nan,        nan,
               nan], device='cuda:0', grad_fn=<Unique2Backward0>)
ClassificationModel output: torch.Size([4, 4, 4, 9, 1]) tensor([5.5868e-07, 9.8171e-07, 9.9230e-07, 9.9399e-07, 1.2773e-06, 2.1170e-06,
        2.4243e-06, 2.5095e-06, 2.6303e-06, 2.9097e-06, 3.7668e-06, 4.6759e-06,
        4.7716e-06, 4.8444e-06, 4.9076e-06, 5.1408e-06, 5.3989e-06, 5.6797e-06,
        5.8639e-06, 6.7368e-06, 7.2935e-06, 7.7259e-06, 8.2689e-06, 8.2736e-06,
        8.4368e-06, 8.5768e-06, 8.5947e-06, 8.6851e-06, 1.0456e-05, 1.1409e-05,
        1.1753e-05, 1.1900e-05, 1.1972e-05, 1.3386e-05, 1.4709e-05, 1.6937e-05,
        1.7014e-05, 1.7106e-05, 1.7218e-05, 1.7498e-05, 1.7688e-05, 1.8227e-05,
        1.9184e-05, 1.9428e-05, 2.0390e-05, 2.0555e-05, 2.1699e-05, 2.1926e-05,
        2.1977e-05, 2.2756e-05, 2.2772e-05, 2.3027e-05, 2.4561e-05, 2.5288e-05,
        2.6400e-05, 2.8776e-05, 3.0203e-05, 3.0807e-05, 3.1708e-05, 3.1952e-05,
        3.2390e-05, 3.5116e-05, 3.5346e-05, 3.5565e-05, 3.5640e-05, 3.6313e-05,
        3.8125e-05, 3.8299e-05, 3.9754e-05, 4.0254e-05, 4.1835e-05, 4.2007e-05,
        4.2550e-05, 4.2887e-05, 4.3390e-05, 4.4604e-05, 4.7997e-05, 4.8839e-05,
        4.9780e-05, 5.0225e-05, 5.1188e-05, 5.4519e-05, 5.6498e-05, 5.9101e-05,
        5.9733e-05, 6.4592e-05, 6.6393e-05, 6.6551e-05, 6.6752e-05, 7.0257e-05,
        7.1969e-05, 7.2054e-05, 7.2106e-05, 7.3252e-05, 7.4446e-05, 7.5162e-05,
        7.5360e-05, 8.0969e-05, 8.1722e-05, 8.1871e-05, 8.2689e-05, 8.3529e-05,
        8.3814e-05, 8.4607e-05, 8.4651e-05, 8.9966e-05, 9.0253e-05, 9.2593e-05,
        9.3255e-05, 9.8466e-05, 1.0100e-04, 1.0115e-04, 1.0182e-04, 1.0662e-04,
        1.1025e-04, 1.1072e-04, 1.1185e-04, 1.1276e-04, 1.1681e-04, 1.1705e-04,
        1.1927e-04, 1.2029e-04, 1.2210e-04, 1.2450e-04, 1.2527e-04, 1.2643e-04,
        1.2808e-04, 1.2989e-04, 1.3246e-04, 1.3246e-04, 1.3519e-04, 1.3719e-04,
        1.3753e-04, 1.4037e-04, 1.4912e-04, 1.5536e-04, 1.5724e-04, 1.5823e-04,
        1.6323e-04, 1.6571e-04, 1.6785e-04, 1.6860e-04, 1.6992e-04, 1.7485e-04,
        1.7663e-04, 1.8386e-04, 1.8530e-04, 1.8622e-04, 1.9134e-04, 1.9346e-04,
        1.9502e-04, 1.9570e-04, 2.0383e-04, 2.0665e-04, 2.0687e-04, 2.0816e-04,
        2.0939e-04, 2.1290e-04, 2.1621e-04, 2.2021e-04, 2.2453e-04, 2.2588e-04,
        2.3147e-04, 2.3171e-04, 2.3263e-04, 2.3384e-04, 2.3416e-04, 2.3467e-04,
        2.3687e-04, 2.3721e-04, 2.4007e-04, 2.4028e-04, 2.5373e-04, 2.5465e-04,
        2.5735e-04, 2.6792e-04, 2.6880e-04, 2.7032e-04, 2.7210e-04, 2.7212e-04,
        2.7378e-04, 2.7773e-04, 2.7887e-04, 2.7959e-04, 2.8760e-04, 2.9795e-04,
        3.0204e-04, 3.0396e-04, 3.0860e-04, 3.0988e-04, 3.1169e-04, 3.1726e-04,
        3.1927e-04, 3.2130e-04, 3.2588e-04, 3.2867e-04, 3.3778e-04, 3.3916e-04,
        3.3961e-04, 3.4170e-04, 3.4797e-04, 3.5074e-04, 3.5505e-04, 3.5826e-04,
        3.7032e-04, 3.7834e-04, 3.7906e-04, 3.8123e-04, 3.8665e-04, 4.0647e-04,
        4.0902e-04, 4.0984e-04, 4.1148e-04, 4.2029e-04, 4.3044e-04, 4.3372e-04,
        4.3689e-04, 4.3829e-04, 4.4524e-04, 4.4747e-04, 4.4753e-04, 4.5718e-04,
        4.6565e-04, 4.6783e-04, 4.7071e-04, 4.7143e-04, 4.7457e-04, 4.8135e-04,
        4.8578e-04, 4.9723e-04, 4.9784e-04, 4.9826e-04, 5.0241e-04, 5.0540e-04,
        5.1115e-04, 5.1345e-04, 5.2171e-04, 5.2888e-04, 5.5271e-04, 5.6601e-04,
        5.6844e-04, 5.6941e-04, 5.7322e-04, 5.7447e-04, 5.8538e-04, 6.0374e-04,
        6.1413e-04, 6.1810e-04, 6.2014e-04, 6.2245e-04, 6.2345e-04, 6.3045e-04,
        6.3264e-04, 6.5229e-04, 6.5282e-04, 6.6051e-04, 6.6160e-04, 6.6438e-04,
        6.8975e-04, 7.0461e-04, 7.1196e-04, 7.2594e-04, 7.3427e-04, 7.5544e-04,
        7.6478e-04, 7.6593e-04, 7.6718e-04, 7.6977e-04, 7.8221e-04, 7.9222e-04,
        7.9462e-04, 7.9711e-04, 7.9955e-04, 8.1445e-04, 8.1530e-04, 8.3143e-04,
        8.3945e-04, 8.8149e-04, 8.8354e-04, 8.9231e-04, 8.9844e-04, 9.1140e-04,
        9.1508e-04, 9.3682e-04, 9.3911e-04, 9.8995e-04, 9.9052e-04, 1.0289e-03,
        1.0424e-03, 1.0428e-03, 1.0819e-03, 1.1073e-03, 1.1120e-03, 1.1176e-03,
        1.1529e-03, 1.1585e-03, 1.1732e-03, 1.2064e-03, 1.2277e-03, 1.3503e-03,
        1.3730e-03, 1.3828e-03, 1.3921e-03, 1.4201e-03, 1.4380e-03, 1.4389e-03,
        1.4451e-03, 1.4671e-03, 1.5098e-03, 1.5988e-03, 1.5997e-03, 1.6111e-03,
        1.6152e-03, 1.6315e-03, 1.6905e-03, 1.7084e-03, 1.7250e-03, 1.8047e-03,
        1.8227e-03, 1.8259e-03, 1.8392e-03, 1.8638e-03, 1.8927e-03, 1.8955e-03,
        1.8993e-03, 1.9033e-03, 1.9472e-03, 2.0366e-03, 2.0788e-03, 2.0802e-03,
        2.0830e-03, 2.2340e-03, 2.2362e-03, 2.2410e-03, 2.2554e-03, 2.2748e-03,
        2.3335e-03, 2.3583e-03, 2.4073e-03, 2.4187e-03, 2.4820e-03, 2.5291e-03,
        2.6643e-03, 2.6659e-03, 2.8492e-03, 2.8663e-03, 2.9550e-03, 3.0120e-03,
        3.1176e-03, 3.1532e-03, 3.2000e-03, 3.2069e-03, 3.2212e-03, 3.2301e-03,
        3.3563e-03, 3.3704e-03, 3.4495e-03, 3.4619e-03, 3.4981e-03, 3.5166e-03,
        3.5466e-03, 3.5809e-03, 3.6190e-03, 3.6275e-03, 3.7801e-03, 3.8044e-03,
        3.8365e-03, 3.9827e-03, 4.1452e-03, 4.2258e-03, 4.2685e-03, 4.3531e-03,
        4.3786e-03, 4.4037e-03, 4.4572e-03, 4.4680e-03, 4.6064e-03, 4.6124e-03,
        4.8186e-03, 4.9285e-03, 4.9405e-03, 5.2137e-03, 5.4138e-03, 5.7709e-03,
        5.8845e-03, 6.4357e-03, 6.5868e-03, 7.9928e-03, 8.1761e-03, 8.7259e-03,
        8.8924e-03, 9.7905e-03, 1.0007e-02, 1.0546e-02, 1.1067e-02, 1.1160e-02,
        1.1498e-02, 1.1616e-02, 1.1639e-02, 1.2340e-02, 1.2722e-02, 1.2839e-02,
        1.2902e-02, 1.3065e-02, 1.3117e-02, 1.3262e-02, 1.3727e-02, 1.4140e-02,
        1.4363e-02, 1.4665e-02, 1.4778e-02, 1.4898e-02, 1.4916e-02, 1.5294e-02,
        1.7223e-02, 1.7307e-02, 1.7376e-02, 1.7855e-02, 1.8460e-02, 1.9665e-02,
        2.0025e-02, 2.0507e-02, 2.0751e-02, 2.1261e-02, 2.2738e-02, 2.4885e-02,
        3.1052e-02, 3.1611e-02, 3.6619e-02, 4.7602e-02, 4.9638e-02, 5.2075e-02,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,        nan],
       device='cuda:0', grad_fn=<Unique2Backward0>)
local_maps torch.Size([4, 128, 128, 9, 1]) tensor([0.0000e+00, 2.9481e-39, 3.1011e-39,  ...,        nan,        nan,
               nan], device='cuda:0', grad_fn=<Unique2Backward0>)
Traceback (most recent call last):
  File "train_oxnet.py", line 337, in <module>
    main()
  File "train_oxnet.py", line 212, in main
    classification, regression, anchors, annotations, global_output, cls_features, prototypes = retinanet(
  File "/home/sjyang/anaconda3/envs/yc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sjyang/anaconda3/envs/yc/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/sjyang/anaconda3/envs/yc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ccvl/net/ccvl15/yucheng/Code/Reference/Omni/OXnet/retinanet/model.py", line 407, in forward
    attentions = self._get_local_map(class_maps, global_class_maps.shape[-2:], normalize=True, detach=False)
  File "/ccvl/net/ccvl15/yucheng/Code/Reference/Omni/OXnet/retinanet/model.py", line 295, in _get_local_map
    lmap = F.interpolate(lmap.unsqueeze(0).unsqueeze(0), size=reshap_size,
AttributeError: 'NoneType' object has no attribute 'unsqueeze'

**Comment by LLYXC** [comment]
Usually, Nan occurs when there are zero divisions in the code. As I have not come across the same problem here before, I cannot simply debug based on the error message posted here.

You may contact me through my email with more details, and let's see where the problem is.

**Comment by johnson111788** [comment]
Sounds good.

I've contacted you through the QQ mail you left on your website.
